<a href="https://colab.research.google.com/github/makifcevik/tf-practise/blob/main/tf_practise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf
import numpy as np

In [ ]:
tensor_0d = tf.constant(4)
print(tensor_0d)

tf.Tensor(4, shape=(), dtype=int32)


In [ ]:
tensor_1d = tf.constant([2, 0, -3.])
print(tensor_1d)

tf.Tensor([ 2.  0. -3.], shape=(3,), dtype=float32)


In [ ]:
tensor_2d = tf.constant([
    [0, 3, -5],
    [5, 3, -1],
    [7, -10, 1],
    [-4, 0, 6],
])
print(tensor_2d)

tf.Tensor(
[[  0   3  -5]
 [  5   3  -1]
 [  7 -10   1]
 [ -4   0   6]], shape=(4, 3), dtype=int32)


In [ ]:
tensor_3d = tf.constant(
    [
        [
            [1, 2, 3],
            [4, 5, 6]
        ],
        [
            [7, 8, 9],
            [10, 11, 12]
        ],
        [
            [13, 14, 15],
            [16, 17, 18]
        ],
        [
            [19, 20, 21],
            [22, 23, 24]
        ]
    ]
)
print(tensor_3d)

tf.Tensor(
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]]], shape=(4, 2, 3), dtype=int32)


In [ ]:
tensor_1d = tf.constant([1, 0, 2., -5])
# casted_tensor = tf.cast(tensor_1d, tf.int32)
casted_tensor = tf.cast(tensor_1d, tf.bool)
print(tensor_1d)
print(casted_tensor)

tf.Tensor([ 1.  0.  2. -5.], shape=(4,), dtype=float32)
tf.Tensor([ True False  True  True], shape=(4,), dtype=bool)


In [ ]:
tensor_string = tf.constant(["hello", "hi", "hey"])
print(tensor_string)

tf.Tensor([b'hello' b'hi' b'hey'], shape=(3,), dtype=string)


In [ ]:
array = np.arange(0, 10, 2)
converted_array = tf.convert_to_tensor(array)
print(converted_array)

tf.Tensor([0 2 4 6 8], shape=(5,), dtype=int64)


In [ ]:
eye_tensor = tf.eye(
    num_rows=5,
    num_columns=3,
    # batch_shape=[3, 2]
)
print(eye_tensor)

tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]
 [0. 0. 0.]], shape=(5, 3), dtype=float32)


In [ ]:
fill_tensor = tf.fill([2, 5], 7)
print(fill_tensor)
ones_tensor = tf.ones([3, 4])
print(ones_tensor)
zeros_tensor = tf.zeros([8, 1])
print(zeros_tensor)
bool_tensor = tf.cast(zeros_tensor, tf.bool)
print(bool_tensor)

tf.Tensor(
[[7 7 7 7 7]
 [7 7 7 7 7]], shape=(2, 5), dtype=int32)
tf.Tensor(
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]], shape=(3, 4), dtype=float32)
tf.Tensor(
[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]], shape=(8, 1), dtype=float32)
tf.Tensor(
[[False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]], shape=(8, 1), dtype=bool)


In [ ]:
np_array = np.zeros([3, 6])
tensor = tf.convert_to_tensor(np_array)
ones_tensor = tf.ones_like(tensor)
print(ones_tensor)

tf.Tensor(
[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]], shape=(3, 6), dtype=float64)


# Yeni Bölüm