<a href="https://colab.research.google.com/github/makifcevik/tf-practise/blob/main/tf_practise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import tensorflow as tf
import numpy as np

In [ ]:
tensor_0d = tf.constant(4)
print(tensor_0d)

tf.Tensor(4, shape=(), dtype=int32)


In [ ]:
tensor_1d = tf.constant([2, 0, -3.])
print(tensor_1d)

tf.Tensor([ 2.  0. -3.], shape=(3,), dtype=float32)


In [ ]:
tensor_2d = tf.constant([
    [0, 3, -5],
    [5, 3, -1],
    [7, -10, 1],
    [-4, 0, 6],
])
print(tensor_2d)

tf.Tensor(
[[  0   3  -5]
 [  5   3  -1]
 [  7 -10   1]
 [ -4   0   6]], shape=(4, 3), dtype=int32)


In [ ]:
tensor_3d = tf.constant(
    [
        [
            [1, 2, 3],
            [4, 5, 6]
        ],
        [
            [7, 8, 9],
            [10, 11, 12]
        ],
        [
            [13, 14, 15],
            [16, 17, 18]
        ],
        [
            [19, 20, 21],
            [22, 23, 24]
        ]
    ]
)
print(tensor_3d)

tf.Tensor(
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]]], shape=(4, 2, 3), dtype=int32)


In [ ]:
tensor_1d = tf.constant([1, 0, 2., -5])
# casted_tensor = tf.cast(tensor_1d, tf.int32)
casted_tensor = tf.cast(tensor_1d, tf.bool)
print(tensor_1d)
print(casted_tensor)

tf.Tensor([ 1.  0.  2. -5.], shape=(4,), dtype=float32)
tf.Tensor([ True False  True  True], shape=(4,), dtype=bool)


In [ ]:
tensor_string = tf.constant(["hello", "hi", "hey"])
print(tensor_string)

tf.Tensor([b'hello' b'hi' b'hey'], shape=(3,), dtype=string)


In [ ]:
array = np.arange(0, 10, 2)
converted_array = tf.convert_to_tensor(array)
print(converted_array)

tf.Tensor([0 2 4 6 8], shape=(5,), dtype=int64)


In [ ]:
eye_tensor = tf.eye(
    num_rows=5,
    num_columns=3,
    # batch_shape=[3, 2]
)
print(eye_tensor)

tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]
 [0. 0. 0.]], shape=(5, 3), dtype=float32)


In [ ]:
fill_tensor = tf.fill([2, 5], 7)
print(fill_tensor)
ones_tensor = tf.ones([3, 4])
print(ones_tensor)
zeros_tensor = tf.zeros([8, 1])
print(zeros_tensor)
bool_tensor = tf.cast(zeros_tensor, tf.bool)
print(bool_tensor)

tf.Tensor(
[[7 7 7 7 7]
 [7 7 7 7 7]], shape=(2, 5), dtype=int32)
tf.Tensor(
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]], shape=(3, 4), dtype=float32)
tf.Tensor(
[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]], shape=(8, 1), dtype=float32)
tf.Tensor(
[[False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]], shape=(8, 1), dtype=bool)


In [ ]:
np_array = np.zeros([3, 6])
tensor = tf.convert_to_tensor(np_array)
ones_tensor = tf.ones_like(tensor)
print(ones_tensor)

tf.Tensor(
[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]], shape=(3, 6), dtype=float64)


In [ ]:
print(tf.shape(tensor_3d))
print(tf.rank(tensor_3d))
print(tf.size(tensor_3d))

tf.Tensor([4 2 3], shape=(3,), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor(24, shape=(), dtype=int32)


In [ ]:
random_tensor = tf.random.normal(
    shape=[2,3],
    mean=1.0,
    stddev=1.0
)
print(random_tensor)

tf.Tensor(
[[ 1.2341671   0.39406025 -0.15055466]
 [ 3.0897815   0.12669283  1.6548947 ]], shape=(2, 3), dtype=float32)


In [ ]:
random_tensor = tf.random.uniform(
    shape=[7,],
    minval=0,
    maxval=5
)
print(random_tensor)

tf.Tensor(
[0.8734119  4.801174   4.6858797  2.5690799  1.7672366  0.67584574
 0.10143399], shape=(7,), dtype=float32)


In [ ]:
indexed_tensor = tf.constant([
    [1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]
])
print(indexed_tensor[1:3, 2:])

tf.Tensor(
[[6]
 [9]], shape=(2, 1), dtype=int32)


In [ ]:
abs_tensor = tf.abs(tf.constant([3, 5, -4, 0, -9]))
print(abs_tensor)

tf.Tensor([3 5 4 0 9], shape=(5,), dtype=int32)


In [ ]:
abs_tensor = tf.abs(tf.constant([[4 + 3j], [12 - 5j]]))
print(abs_tensor)

tf.Tensor(
[[ 5.]
 [13.]], shape=(2, 1), dtype=float64)


In [ ]:
x1 = tf.constant([[4, 16, 7], [9, 5, 0]], dtype=tf.float32)
print(tf.sqrt(x1))

tf.Tensor(
[[2.        4.        2.6457512]
 [3.        2.236068  0.       ]], shape=(2, 3), dtype=float32)


In [ ]:
x1 = tf.constant([5, 0, -10, 8], dtype=tf.float32)
x2 = tf.constant([3, 1, 6, -2], dtype=tf.float32)
print(tf.multiply(x1, x2))
print(tf.divide(x2, x1))
print(tf.math.divide_no_nan(x2, x1))

tf.Tensor([ 15.   0. -60. -16.], shape=(4,), dtype=float32)
tf.Tensor([ 0.6    inf -0.6  -0.25], shape=(4,), dtype=float32)
tf.Tensor([ 0.6   0.   -0.6  -0.25], shape=(4,), dtype=float32)


In [ ]:
x1 = tf.constant([3, 12, 5, -7])
x2 = tf.constant([3])
# x2 stretches to match x1
print(tf.add(x1, x2))
print(tf.add(x2, x1))

tf.Tensor([ 6 15  8 -4], shape=(4,), dtype=int32)
tf.Tensor([ 6 15  8 -4], shape=(4,), dtype=int32)


In [ ]:
x1 = tf.constant([-5, 3, 0])
x2 = tf.constant([[4], [0], [-2], [1]])
# x1 stretches to match x2
print(tf.subtract(x1, x2))

tf.Tensor(
[[-9 -1 -4]
 [-5  3  0]
 [-3  5  2]
 [-6  2 -1]], shape=(4, 3), dtype=int32)


In [ ]:
x1 = tf.constant([-10, 5, 1, 0, 12, 9])
# argmax and argmin returns the index
print(tf.argmax(x1))
print(tf.argmin(x1))

tf.Tensor(4, shape=(), dtype=int64)
tf.Tensor(0, shape=(), dtype=int64)


In [ ]:
x2 = tf.constant([
    [1, 2, 4, 7],
    [3, 0, 1, 5]
])
print(tf.argmax(x2, axis=0))  # fix the rows and compare vertically
print(tf.argmax(x2, axis=1))  # fix the columns and compare horizontally

tf.Tensor([1 0 0 0], shape=(4,), dtype=int64)
tf.Tensor([3 3], shape=(2,), dtype=int64)


In [ ]:
x1 = tf.constant([[1, 3], [2, 5]])
x2 = tf.constant([[0, 2], [1, 3]])
print(tf.pow(x1, x2))

tf.Tensor(
[[  1   9]
 [  2 125]], shape=(2, 2), dtype=int32)


In [2]:
x1 = tf.constant([
    [10, 2, 5],
    [2, -5, 7],
    [6, 2, 12],
    [-4, -8, -20]
], dtype=tf.float32)
# reduces all values to one desired value
print(tf.reduce_sum(x1))
print(tf.reduce_max(x1))
print(tf.reduce_min(x1))
print(tf.reduce_mean(x1))
print(tf.math.reduce_std(x1))
print(tf.reduce_sum(x1, axis=0))
print(tf.reduce_sum(x1, axis=1))

tf.Tensor(9.0, shape=(), dtype=float32)
tf.Tensor(12.0, shape=(), dtype=float32)
tf.Tensor(-20.0, shape=(), dtype=float32)
tf.Tensor(0.75, shape=(), dtype=float32)
tf.Tensor(8.486509, shape=(), dtype=float32)
tf.Tensor([14. -9.  4.], shape=(3,), dtype=float32)
tf.Tensor([ 17.   4.  20. -32.], shape=(4,), dtype=float32)


In [10]:
x1 = tf.constant([
    [10, 2, 5],
    [2, -5, 7],
    [6, 2, 12],
    [-4, -8, -20]
], dtype=tf.float32)
print(tf.math.top_k(x1), "\n\n")  # returns the indices of the top k values in each row. (k=1 default)
print(tf.math.top_k(x1, k=2))

TopKV2(values=<tf.Tensor: shape=(4, 1), dtype=float32, numpy=
array([[10.],
       [ 7.],
       [12.],
       [-4.]], dtype=float32)>, indices=<tf.Tensor: shape=(4, 1), dtype=int32, numpy=
array([[0],
       [2],
       [2],
       [0]], dtype=int32)>) 


TopKV2(values=<tf.Tensor: shape=(4, 2), dtype=float32, numpy=
array([[10.,  5.],
       [ 7.,  2.],
       [12.,  6.],
       [-4., -8.]], dtype=float32)>, indices=<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[0, 2],
       [2, 0],
       [2, 0],
       [0, 1]], dtype=int32)>)


In [11]:
x1 = tf.constant([10, -10, 9, 80, 79, 5, -23, 49])
print(tf.math.top_k(x1), "\n\n")
print(tf.math.top_k(x1, k=3))

TopKV2(values=<tf.Tensor: shape=(1,), dtype=int32, numpy=array([80], dtype=int32)>, indices=<tf.Tensor: shape=(1,), dtype=int32, numpy=array([3], dtype=int32)>) 


TopKV2(values=<tf.Tensor: shape=(3,), dtype=int32, numpy=array([80, 79, 49], dtype=int32)>, indices=<tf.Tensor: shape=(3,), dtype=int32, numpy=array([3, 4, 7], dtype=int32)>)


In [16]:
x1 = tf.constant([[1, 2, 3],
                  [4, 5, 6]])
x2 = tf.constant([[1, 2],
                  [3, 4],
                  [5, 6]])
# not element-wise multipication, this is matrix multipication
print(tf.linalg.matmul(x1, x2))
# @ operator is a matrix multipication operator
print(x1 @ x2)

tf.Tensor(
[[22 28]
 [49 64]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[22 28]
 [49 64]], shape=(2, 2), dtype=int32)


In [3]:
x1 = tf.constant([[1, 2, 3],
                  [4, 5, 6]])
print(tf.transpose(x1))

tf.Tensor(
[[1 4]
 [2 5]
 [3 6]], shape=(3, 2), dtype=int32)
